### ISSUE TITLE
Colour picker in popup widget remains open 

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#528] opened 2017-01-05 10:01 UTC
If the colour button in the popup (term info) widget is the first thing clicked (after selecting an item) then the colour selector doesn't appear.
See http://vfbsandbox3.inf.ed.ac.uk:8180/org.geppetto.frontend/geppetto?load_project_from_url=http://vfbsandbox3.inf.ed.ac.uk/do/geppettoJson.json?i=VFB_00013598,VFB_00004549,VFB_00030670%26t=VFBt_001%26d= 

Also remains open even after another object is selected.

**Comment by gidili** [comment] 2017-01-06 10:57
@Robbie1977 I can see that the colour picker doesn't close unless you click somewhere else within the boundaries of the popup widget and that's an issue for sure.

I am unsure with regards to the colour selector not showing up. 

Do you mean that when you click on the colour icon the colour picker doesn't show up at all if that's the first thing you do after selecting? I am trying but can't seem to get it to happen.

**Comment by Robbie1977** [comment] 2017-01-08 11:13
Yep that does seem to have vanished, sorry.

**Comment by gidili** [comment] 2017-01-08 22:05
No worries, let's keep an eye out for strange behaviour and fix the other one (not disappearing) in the meanwhile 👍

**Comment by gidili** [comment] 2017-01-22 21:30
@Robbie1977 there is [a fix]([url](https://github.com/openworm/org.geppetto.frontend/commit/c67e210f89b522a1ccdf35208ecc0a4892815b2f#diff-b26151cefd19a7eb22e03664ca8b1410R352)) on development for this, let me know when you get the chance to test and we can close it then. Tested on chrome and firefox. 

The issue is that we have code in place to prevent foxu being set on canvas elements (for example the geppetto background with the 3d scene and the stack viewer canvas) so when the user clicks on canvas elements (very likely since it's a lot of real estate of screen + background) the color picker doesn't lose focus (or similar).

The technical solution is not particularly elegant but it's the best I could come up with (listen to clicks, do a bunch of checks to see if the target is outside the popup that hosts that color picker and hide it if so).

cc: @tarelli

**Comment by gidili** [comment] 2017-01-26 10:25
@Robbie1977 did you get a chance to test this? If so feel free to close

**Closed** 2017-01-26 12:00 UTC
Labels: bug
