### ISSUE TITLE
Drawing synaptic connections

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#241] opened 2015-02-04 12:59 UTC
Geppetto should honor NeuroML's _pre/post fractionAlong_ attributes, which specify from/to which connection "line" should be drawn in the context of a "compartment" (e.g. from 3/4 of the length of cylinder "pre"  to the middle of cylinder "post").

**Comment by borismarin** [comment] 2015-02-04 13:12
Domain specific. Moved to [OSB](https://github.com/OpenSourceBrain/redmine/issues/149).

**Comment by pgleeson** [comment] 2016-09-08 17:16
Duplicate of https://github.com/openworm/org.geppetto/issues/463

**Closed by pgleeson** 2016-09-08 17:16 UTC
Labels: ideas
